name: Single Job Test
on: [push]

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install .
          pip install fastapi uvicorn requests click

      - name: Start backend server
        run: |
          uvicorn server.app:app --host 0.0.0.0 --port 8000 &
          sleep 3

      - name: Start worker
        run: |
          python server/worker.py &
          sleep 2

      - name: Submit single test job via CLI
        run: |
            qgjob submit --org-id=qualgent --app-version-id=xyz123 --test=tests/onboarding.spec.js --wait
