name: Test Job Runs
on: [push]

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install .
          pip install fastapi uvicorn requests click

      - name: Start backend server
        run: |
          uvicorn server.app:app --host 0.0.0.0 --port 8000 &
          sleep 3

      - name: Start worker
        run: |
          python server/worker.py &
          sleep 2

      - name: Submit test jobs via CLI with wait (no set priority / same priority)
        run: |
            qgjob submit --org-id=qualgent --app-version-id=xyz123 --test=tests/test.spec.ts --wait
            qgjob submit --org-id=qualgent --app-version-id=xyz123 --test=tests/onboarding.spec.js --wait

      - name: Submit multiple test jobs via CLI with no wait (jobs will completed by priority)
        run: |
            qgjob submit --org-id=qualgent --app-version-id=xyz123 --test=tests/login_flow.spec.js --priority=4 --wait
            qgjob submit --org-id=qualgent --app-version-id=abc456 --test=tests/signup_validation.spec.js --priority=2 --wait
            qgjob submit --org-id=qualgent --app-version-id=abc456 --test=tests/profile_update.spec.js --priority=3 --wait
        continue-on-error: false
